task 2

diff --git a/ssh/1-create_ssh_key_pair b/ssh/1-create_ssh_key_pair
--- a/ssh/1-create_ssh_key_pair
+++ b/ssh/1-create_ssh_key_pair
@@ -2,4 +2,12 @@
 # Create SSH key pair with RSA algorithm, 4096 bits, and passphrase "betty"
 ssh-keygen -t rsa -b 4096 -C "school" -f school -N "betty"
 
+# Check if the private key file is in RSA format
+if openssl rsa -in school -noout -text &> /dev/null; then
+    echo "Private key is in RSA format."
+else
+    echo "Error: Private key is not in RSA format."
+    exit 1
+fi
+
 echo "SSH key pair created successfully."
